Adding mods to vim, zsh, and base of colorized calendar

diff --git a/profiles/zshenv b/profiles/zshenv
--- a/profiles/zshenv
+++ b/profiles/zshenv
@@ -1,3 +1,34 @@
 #!/bin/zsh
 
+export PROMPT_COMMAND=__prompt_command    # Function to generate PS1 after CMDs
+
+# https://stackoverflow.com/questions/16715103/bash-prompt-with-the-last-exit-code
+__prompt_command() {
+    local EXIT="$?"                # This needs to be first
+    local _PS1=""
+
+    local RCol='\[\e[0m\]'
+
+    local Red='\[\e[0;31m\]'
+    local BRed='\[\e[1;31m\]'
+    local Gre='\[\e[0;36m\]'
+    local BGre='\[\e[1;36m\]'
+    local BYel='\[\e[1;33m\]'
+    local BBlu='\[\e[1;34m\]'
+    local Pur='\[\e[0;35m\]'
+
+    if [ $EXIT != 0 ]; then
+        _PS1+="${BRed}⇡⇡⇡⇡⇡⇡⇡⇡⇡⇡⇡⇡ ⏱  \D{%Y-%m-%dT%H:%M:%S-05:00} 🛑  [${EXIT}]${RCol}"        # Add red if exit code non 0
+    else
+        _PS1+="${BGre}⇡⇡⇡⇡⇡⇡⇡⇡⇡⇡⇡⇡ ⏱  \D{%Y-%m-%dT%H:%M:%S-05:00} 🟢  ${RCol}"
+    fi
+
+    _PS1+="\n--------------------------------------------------------------------\n"
+    _PS1+="⇣⇣⇣⇣⇣⇣⇣⇣⇣⇣⇣⇣ 💻 \u@${BBlu}\h ${Pur}\W${BYel}$ ${RCol}"
+
+    export PS1="${_PS1}"
+}
+
+
 precmd_functions=(week_prompt)
+# precmd_functions=(__prompt_command)
